config/routes.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
Rails.application.routes.draw do
  
  get 'welcome/index'
  root to: "catalog/welcome#index"
  
  namespace :account do
    # resources after registration on devise add user first_name, last_name ... select role etc...
    resources :steps, only: [:show, :update]
    # resources manufacturer registration company, trademark, product etc...
    resources :manufacturer_steps, only: [:show, :update]
    # resources distributor registration company etc...
    resources :distributor_steps, only: [:show, :update]
  end

  namespace :catalog do
    get "/" => "products#index"
    resources :trademarks, only: [:index, :show]
    resources :companies, only: [:index, :show]
    # resources :categories, only: [:index, :show] do
    #   resources :products, only: [:index, :show] do
    #     member do
    #       get :like
    #       get :unlike
    #     end
    #   end
    # end
    
    resources :categories, only: [:index, :show]
    resources :products, only: [:index, :show] do
      member do
        put :like
        put :unlike
        put :favorite
        put :unfavorite
      end
    end
  resources :customers, only: [:index, :show] do
      member do
        put :follow
        put :unfollow
      end
    end
  end
  
  namespace :administration do
    get "/" => "dashboard#index"
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end

    resources :trademarks, only: [:index, :show, :edit, :update]
    #match 'roles/index', to: 'roles#index', as: :roles, via: 'get'
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get :manufacturers
        get :distributors
        get :simple_customers
        get :all
      end
    end
    resources :employees, only: [:index, :show, :edit, :update] do
      collection do
        get :administrators
        get :moderators
        get :operators
        get :all
      end
    end
    resources :users
    resources :companies, only: [:index, :show, :edit, :update] do
      collection do
        get :published#, path: "/states/published"
        get :pending
        get :editing
        get :denied
        get :trashed
        get :removed
      end
    end
    scope "/stadistics" do
      resources :activities
    end
    scope "/catalog" do
      resources :categories
      resources :products, only: [:index, :show, :edit, :update] do
         collection do
          match 'search' => 'products#search', via: [:get, :post], as: :search
        end
      end
    end

    scope "/account" do

      match 'dashboard',  to: 'dashboard#index', as: :dashboard, via: [:get] 
      match 'profile', to: 'account#profile', as: :profile, via: 'get'

    end
    scope "/administration" do
      #match 'employees/list', to: 'employees#index', as: :employees, via: 'get'
      # TheRoleManagementPanel::Routes.mixin(self)
      resources :roles
      resources :activities
    end
  end

  #scope :account do
 
    resources :users do
      member do
        put :follow
        put :unfollow
      end
    end

    resources :product_images
    resources :companies
    resources :trademarks
    resources :categories, only: [:index, :show] do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end
    resources :subcategories
    resources :products

 
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end
    
    scope "/account" do
      get 'dashboard',  to: 'dashboard#index', as: :dashboard
      get 'profile', to: 'account#profile', as: :profile
      match 'profile/update', to: 'account#update_profile', as: :update_profile, via: [:patch, :put] 
      get 'profile/edit', to: 'account#edit_profile', as: :edit_profile
      match 'my_favorite_products', to: 'account#my_favorite_products', as: :my_favorite_products, via: 'get'
    end
     
    #TheRoleManagementPanel::Routes.mixin(self)
    #devise_for :users, :path => '', controllers: {registrations: 'users/registrations'}
    
  #end

  devise_for :users, :path => '', controllers: { registrations: "registrations" }
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/controllers/administration/activities_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end 
class Administration::ActivitiesController < ApplicationController
  before_action :login_required
  before_action :role_required

  def index
  	#@activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.brand_ids, owner_type: "User")
  	@activities = PublicActivity::Activity.all.order("created_at desc").paginate(:page => params[:page], :per_page => 10).order(created_at: :desc)
  end
end

app/controllers/administration/categories_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::CategoriesController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  def index
    #@categories = Category.all.paginate(:page => params[:page], :per_page => 10)
    @categories = Category.paginate(:page => params[:page], :per_page => 10)
  end

  def show
   # alls categories
    @categories = Category.parent_categories(@category)
    # current category
    @category = Category.find(params[:id])
    
    #@activities = PublicActivity::Activity.order("created_at DESC").where(trackable_type: "Category", trackable_id: @category).all
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html {
          if params[:stay] 
            redirect_to edit_administration_category_path(@category)
            toast :success, "Категория #{@category.name} была успешно создана."
          else
            redirect_to administration_categories_path
            toast :success, "Категория #{@category.name} была успешно создана."
          end
        }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {
          if params[:stay] 
            redirect_to edit_administration_category_path(@category)
            toast :success, "Категория #{@category.name} была успешно обновлена."
          else
            redirect_to administration_categories_path
            toast :success, "Категория #{@category.name} была успешно обновлена."
          end
        }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |format|
      format.html { 
        redirect_to administration_categories_url
        toast :success, "Категория была успешно удалена."
      }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      begin
      @category = Category.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        toast :success, "Категория не найдена."
        toast :success, "Категория под номером #{params[:id]} не найдена."
        
        redirect_to administration_categories_path
      end
    end

    def category_params
      params.require(:category).permit(
        :name,
        :description,
        :meta_title,
        :meta_keywords,
        :meta_description,
        :status,
        :parent_id,
        :lft,
        :rgt,
        :depth,
        :children_count
      )
    end
end

app/controllers/administration/companies_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::CompaniesController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    # @companies = Company.all
    # @companies = Company.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    @search = Company.search(params[:q])
    @companies = @search.result.paginate(:page => params[:page], :per_page => 30)
  end

  def published
    @companies = Company.published.paginate(:page => params[:page], :per_page => 30)
  end

  def pending
    @companies = Company.pending.paginate(:page => params[:page], :per_page => 30)
  end

  def editing
    @companies = Company.editing.paginate(:page => params[:page], :per_page => 30)
  end

  def denied
    @companies = Company.denied.paginate(:page => params[:page], :per_page => 30)
  end

  def trashed
    @companies = Company.trashed.paginate(:page => params[:page], :per_page => 30)
  end

  def removed
    @companies = Company.removed.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  # def new
  #   @company = Company.new
  # end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  # def create
  #   @company = Company.new(company_params)

  #   respond_to do |format|
  #     if @company.save
  #       format.html { 
  #         redirect_to administration_company_path(@company)
  #         toast :success, "Компания была успешно создана."
  #       }
  #       format.json { render :show, status: :created, location: @company }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @company.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { 
          redirect_to administration_company_path(@company)
          toast :success, "Компания была успешно обновлена."
        }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { 
        redirect_to administration_companies_url
        toast :success, "Компания была успешно удалена."
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(
        :logo,
        :name,
        :description,
        :business_entity,
        :vatcode,
        :company_id_number,
        :cea,
        :registration_date,
        :address,
        :meta_title,
        :meta_keywords,
        :meta_description,
        :state_event
      )
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/controllers/administration/customers_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::CustomersController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_customer, only: [:show, :edit, :update, :destroy, :follow_button]
  
  def index 
    redirect_to all_administration_customers_path  
  end

  def all
    manufacturer = Role.with_name(:manufacturer).id
    distributor = Role.with_name(:distributor).id
    simple_customer = Role.with_name(:simple_customer).id
    
    @customers = User.all_customers([simple_customer, distributor, manufacturer]).search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    #@employee = User.paginate(:page => params[:page], :per_page => 10).order(last_name: :desc)
  end

  def manufacturers
    @customers = User.manufacturers.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  def distributors
    @customers = User.distributors.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  def simple_customers
    @customers = User.simple_customers.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  def show
    if @customer.company.try(:any?)
      #@featured_products = @customer.company.products.filter(params.slice(:status, :location, :starts_with)).last(12)
      @featured_products = @customer.company.products.last(12)
    else
      #redirect_to :root
      @featured_products = nil
      toast :error, "Ошибка."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = User.find(params[:id])
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/controllers/administration/dashboard_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::DashboardController < ApplicationController
  before_action :login_required
  before_action :role_required

  def index
    @users = User.all
  end
end

app/controllers/administration/product_images_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::ProductImagesController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_product_image, only: [:show, :edit, :update, :destroy]

  # GET /product_images
  # GET /product_images.json
  def index
    @product_images = ProductImage.all
  end

  # GET /product_images/1
  # GET /product_images/1.json
  def show
  end

  # GET /product_images/new
  def new
    @product_image = ProductImage.new
  end

  # GET /product_images/1/edit
  def edit
  end

  # POST /product_images
  # POST /product_images.json
  def create
    @product_image = ProductImage.new(product_image_params)

    respond_to do |format|
      if @product_image.save
        format.html { redirect_to @product_image, notice: 'Product image was successfully created.' }
        format.json { render :show, status: :created, location: @product_image }
      else
        format.html { render :new }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_images/1
  # PATCH/PUT /product_images/1.json
  def update
    respond_to do |format|
      if @product_image.update(product_image_params)
        format.html { redirect_to @product_image, notice: 'Product image was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_image }
      else
        format.html { render :edit }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_images/1
  # DELETE /product_images/1.json
  def destroy
    @product_image.destroy
    respond_to do |format|
      format.html { redirect_to product_images_url, notice: 'Product image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_image
      @product_image = ProductImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_image_params
      params.require(:product_image).permit(:product_id, :image)
    end
end

app/helpers/administration/product_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Administration::ProductHelper 
end

app/helpers/administration/trademarks_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Administration::TrademarksHelper  
end

app/helpers/catalog/trademarks_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::TrademarksHelper
end

app/views/administration/trademarks/_assets.erb
<% content_for :css do %>
<%= stylesheet_link_tag "plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox" %>
<%= stylesheet_link_tag "plugins/summernote/summernote.css" %>
<%= stylesheet_link_tag "plugins/summernote/summernote-bs3" %>
<%= stylesheet_link_tag "plugins/datapicker/datepicker3" %>

<% end %>

<% content_for :js do %>
<!-- iCheck -->
<%= javascript_include_tag "plugins/iCheck/icheck.min" %>
<!-- SUMMERNOTE -->
<%= javascript_include_tag "plugins/summernote/summernote.min" %>
<%= javascript_include_tag "plugins/datapicker/bootstrap-datepicker" %>
    <script>
        $(document).ready(function () {
            $('.summernote').summernote();
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
            $('.input-group.date').datepicker({
                todayBtn: "linked",
                language: "ru",
                keyboardNavigation: false,
                forceParse: false,
                calendarWeeks: true,
                autoclose: true
            });

        });
    </script>
<% end %>

app/views/administration/trademarks/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Редактирование торговой марки - <%= @trademark.name if @trademark.name %></h2>
        <ol class="breadcrumb">
            <li><a href="<%= administration_dashboard_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li class="active"><strong>Редактирование торговой марки</strong></li>
        </ol>
    </div>
</div>
<%= render 'assets' %>
<%= render 'form' %>

app/views/administration/trademarks/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Каталог - список торговых марок</h2>
        <ol class="breadcrumb">
            <li><a href="<%= administration_dashboard_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li class="active"><strong>Список торговых марок</strong></li>
        </ol>
    </div>
    <div class="col-lg-2">
        <%#= link_to 'Добавить торговую марку', new_administration_company_path %>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight ecommerce">
    <div class="ibox">
        <div class="ibox-title">
            <h5>Список торговых марок</h5>
            <div class="ibox-tools">
                <%#= link_to content_tag(:i, nil, class: "fa fa-plus") + " " + "Добавить торговую марку", new_administration_trademark_path, class: "btn-primary btn btn-xs" %>
            </div>
        </div>
        <%#= search_form_for @q, url: search_products_path, html: { method: :post }  do |f| %>
        <div class="ibox-content m-b-sm border-bottom">
            <div class="row">
                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label" for="product_name">Название торговой марки</label>
                        <input type="text" id="product_name" name="product_name" value="" placeholder="Название торговой марки" class="form-control">
                        <%#= f.text_field :name_eq, placeholder: "Название товара", class: "form-control" %>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label" for="status">Статус</label>
                        <select name="status" id="status" class="form-control">
                            <option value="1" selected="">Активный
                            <option value="0">Неактивный
                        </select>
                    </div>
                </div>
                <%#= submit_tag "Search" %>
                <%#= submit_tag, class: 'btn btn btn-primary', :name => nil  do  %>
                <%#= content_tag(:i, nil, class: "fa fa fa-search") + ' ' + "Поиск" %>
                <%# end %>
            </div>
        </div>
        <div class="wrapper wrapper-content ecommerce">
            <div class="row">
                <div class="col-lg-12">
                        <div class="ibox-content">
                            <table class="footable table table-stripped toggle-arrow-tiny" data-page-size="15">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Лого</th>
                                        <th data-toggle="true">Название</th>
                                        <th>Компания</th>
                                        <th>ИД компании</th>
                                        <th>Описание</th>
                                        <th>Колич. товаров</th>
                                        <th class="text-right" data-sort-ignore="true">Действие</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   <% @trademarks.each do |at| %>
                                    <tr>
                                        <% if at.status == "published" %> 
                                        <td><span class="small" data-toggle="tooltip" data-placement="top" title="<%= t(at.status, :scope => 'trademark_status') %>"><i class="fa fa fa-circle text-navy"> </i></span></td>
                                        <% else %>
                                        <td><span class="small" data-toggle="tooltip" data-placement="top" title="<%= t(at.status, :scope => 'trademark_status') %>"><i class="fa fa fa-circle text-danger"> </i></span></td>
                                        <% end %>
                                        <td><%= image_tag at.logo_url(:thumb) %></td>
                                        <td><%= link_to at.name, administration_trademark_path(at) if at.company.name %></td>
                                        <td><%= link_to at.company.name, administration_company_path(at.company) if at.company %></td>
                                        <td><%= at.company.company_id_number %></td>
                                        <td><%= raw at.description.truncate(100) if at.description %></td>
                                        <td><%= at.company.products.count if at.company.products %></td>
                                        
                                        <td class="text-right">
                                            <div class="btn-group">
                                                <%= link_to content_tag(:i, nil, class: "fa fa-eye") + " " + "Просмотр", administration_trademark_path(at), class: "btn-white btn btn-xs" %>
                                                <%= link_to content_tag(:i, nil, class: "fa fa-pencil") + " " + "Править", edit_administration_trademark_path(at), class: "btn-white btn btn-xs" %>
                                            </div>
                                        </td>
                                    </tr>
                                    <% end %>
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td colspan="6">
                                            <ul class="pagination pull-right"><%= will_paginate @trademarks %></ul>
                                        </td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                     
                </div>
            </div>
        </div>
    </div>
</div>

app/views/administration/trademarks/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Добавление торговой марки</h2>
        <ol class="breadcrumb">
            <li><a href="<%= administration_dashboard_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li class="active"><strong>Добавление торговой марки</strong></li>
        </ol>
    </div>
</div>
<%= render 'assets' %>
<%= render 'form' %>

app/views/administration/trademarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trademark.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @trademark.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @trademark.user %>
</p>

<p>
  <strong>Company:</strong>
  <%= @trademark.company %>
</p>

<p>
  <strong>Company:</strong>
  <%= @trademark.company %>
</p>

<%= link_to 'Edit', edit_administration_trademark_path(@trademark) %> |
<%= link_to 'Back', administration_trademarks_path %>