config/routes.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
Rails.application.routes.draw do
  
  get 'welcome/index'
  root to: "catalog/welcome#index"
  
  namespace :account do
    # resources after registration on devise add user first_name, last_name ... select role etc...
    resources :steps, only: [:show, :update]
    # resources manufacturer registration company, trademark, product etc...
    resources :manufacturer_steps, only: [:show, :update]
    # resources distributor registration company etc...
    resources :distributor_steps, only: [:show, :update]
  end

  namespace :catalog do
    get "/" => "products#index"
    resources :trademarks, only: [:index, :show]
    resources :companies, only: [:index, :show]
    # resources :categories, only: [:index, :show] do
    #   resources :products, only: [:index, :show] do
    #     member do
    #       get :like
    #       get :unlike
    #     end
    #   end
    # end
    
    resources :categories, only: [:index, :show]
    resources :products, only: [:index, :show] do
      member do
        put :like
        put :unlike
        put :favorite
        put :unfavorite
      end
    end
  resources :customers, only: [:index, :show] do
      member do
        put :follow
        put :unfollow
      end
    end
  end
  
  namespace :administration do
    get "/" => "dashboard#index"
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end

    resources :trademarks, only: [:index, :show, :edit, :update]
    #match 'roles/index', to: 'roles#index', as: :roles, via: 'get'
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get :manufacturers
        get :distributors
        get :simple_customers
        get :all
      end
    end
    resources :employees, only: [:index, :show, :edit, :update] do
      collection do
        get :administrators
        get :moderators
        get :operators
        get :all
      end
    end
    resources :users
    resources :companies, only: [:index, :show, :edit, :update] do
      collection do
        get :published#, path: "/states/published"
        get :pending
        get :editing
        get :denied
        get :trashed
        get :removed
      end
    end
    scope "/stadistics" do
      resources :activities
    end
    scope "/catalog" do
      resources :categories
      resources :products, only: [:index, :show, :edit, :update] do
         collection do
          match 'search' => 'products#search', via: [:get, :post], as: :search
        end
      end
    end

    scope "/account" do

      match 'dashboard',  to: 'dashboard#index', as: :dashboard, via: [:get] 
      match 'profile', to: 'account#profile', as: :profile, via: 'get'

    end
    scope "/administration" do
      #match 'employees/list', to: 'employees#index', as: :employees, via: 'get'
      # TheRoleManagementPanel::Routes.mixin(self)
      resources :roles
      resources :activities
    end
  end

  #scope :account do
 
    resources :users do
      member do
        put :follow
        put :unfollow
      end
    end

    resources :product_images
    resources :companies
    resources :trademarks
    resources :categories, only: [:index, :show] do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end
    resources :subcategories
    resources :products

 
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end
    
    scope "/account" do
      get 'dashboard',  to: 'dashboard#index', as: :dashboard
      get 'profile', to: 'account#profile', as: :profile
      match 'profile/update', to: 'account#update_profile', as: :update_profile, via: [:patch, :put] 
      get 'profile/edit', to: 'account#edit_profile', as: :edit_profile
      match 'my_favorite_products', to: 'account#my_favorite_products', as: :my_favorite_products, via: 'get'
    end
     
    #TheRoleManagementPanel::Routes.mixin(self)
    #devise_for :users, :path => '', controllers: {registrations: 'users/registrations'}
    
  #end

  devise_for :users, :path => '', controllers: { registrations: "registrations" }
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/controllers/administration/companies_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::CompaniesController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    # @companies = Company.all
    # @companies = Company.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    @search = Company.search(params[:q])
    @companies = @search.result.paginate(:page => params[:page], :per_page => 30)
  end

  def published
    @companies = Company.published.paginate(:page => params[:page], :per_page => 30)
  end

  def pending
    @companies = Company.pending.paginate(:page => params[:page], :per_page => 30)
  end

  def editing
    @companies = Company.editing.paginate(:page => params[:page], :per_page => 30)
  end

  def denied
    @companies = Company.denied.paginate(:page => params[:page], :per_page => 30)
  end

  def trashed
    @companies = Company.trashed.paginate(:page => params[:page], :per_page => 30)
  end

  def removed
    @companies = Company.removed.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  # def new
  #   @company = Company.new
  # end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  # def create
  #   @company = Company.new(company_params)

  #   respond_to do |format|
  #     if @company.save
  #       format.html { 
  #         redirect_to administration_company_path(@company)
  #         toast :success, "Компания была успешно создана."
  #       }
  #       format.json { render :show, status: :created, location: @company }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @company.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { 
          redirect_to administration_company_path(@company)
          toast :success, "Компания была успешно обновлена."
        }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { 
        redirect_to administration_companies_url
        toast :success, "Компания была успешно удалена."
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(
        :logo,
        :name,
        :description,
        :business_entity,
        :vatcode,
        :company_id_number,
        :cea,
        :registration_date,
        :address,
        :meta_title,
        :meta_keywords,
        :meta_description,
        :state_event
      )
    end

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ?  params[:direction] : "asc"
    end
end

app/controllers/catalog/companies_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::CompaniesController < ApplicationController
  before_action :set_company, only: [:show]
  layout 'catalog'
  
  # GET /catalog/companies
  # GET /catalog/companies.json
  def index
    #@companies = Company.all
    @companies = Company.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /catalog/companies/1
  # GET /catalog/companies/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/companies_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class CompaniesController < ApplicationController
  before_action :login_required # the role
  before_action :role_required # the role
  # Обезательное расположение колбэков (поначалу сет обьекта, так как в нем есть глобальная переменная, потом проверка на owner).
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :owner_required, only: [:edit, :update, :destroy] # the role
  # GET /account/companies
  # GET /account/companies.json
  def index
    @company = current_user.company
    @featured_products = current_user.products.filter(params.slice(:status, :location, :starts_with)).last(12)
  end

  # GET /account/companies/1
  # GET /account/companies/1.json
  def show
    @featured_products = Product.filter(params.slice(:status, :location, :starts_with)).last(12)
  end

  # GET /account/companies/new
  def new
    @company = current_user.build_company
  end

  # GET /account/companies/1/edit
  def edit
  end

  # POST /account/companies
  # POST /account/companies.json
  def create
    @company = current_user.build_company(company_params)

    respond_to do |format|
      if @company.save
        format.html { 
          redirect_to company_path(@company)
          toast :success, "Компания была успешно создана."
        }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /account/companies/1
  # PATCH/PUT /account/companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html {
          redirect_to company_path(@company)
          toast :success, "Компания была успешно обновлена."
        }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /account/companies/1
  # DELETE /account/companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
      # TheRole: object for ownership checking
      for_ownership_check(@company) # етот находиться в метод в aplication controller
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(
        :user_id,
        :logo,
        :name,
        :description,
        :business_entity,
        :vatcode,
        :company_id_number,
        :cea,
        :registration_date,
        :address,
        :meta_title,
        :meta_keywords,
        :meta_description,
        :state_event
      )
    end
end

app/helpers/catalog/companies_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::CompaniesHelper  
end

app/helpers/companies_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module CompaniesHelper  
end

app/views/companies/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Редактирование компании - <%= @company.name %></h2>
        <ol class="breadcrumb">
            <li><a href="<%= dashboard_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li><a href="<%= companies_path %>">Компании</a></li>
            <li class="active"><strong>Редактирование компании</strong></li>
        </ol>
    </div>
</div>
<%= render 'form' %>

app/views/companies/index.html.erb
<% if @company %>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Профиль компании - <%= @company.name %></h2>
        <ol class="breadcrumb">
            <li><a href="<%= dashboard_path %>">Главная</a></li>
            <li><a>компании</a></li>
            <li class="active"><strong>Профиль</strong></li>
        </ol>
    </div>
    <div class="col-lg-2">
        <%= link_to "Редактировать #{@company.name}", edit_company_path(@company) %>
    </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">
            <div class="profile-image">
                <%= image_tag @company.logo_url(:profile), alt: @company.name %>
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h2 class="no-margins">
                            <%= @company.name %>
                        </h2>
                        <h4><%#= raw current_user.post %> <%#= raw current_user.company.name if current_user.company %></h4>
                        <small>
                            <%= raw @company.description %>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <table class="table small m-b-xs">
                <tbody>
                <tr>
                    <td><strong><%= @company.products.count %></strong>Товаров</td>
                    <td><strong><%#= @company.products.categories.count %></strong>Категории</td>
                </tr>
                <tr>
                    <td>
                        <strong>61</strong> Comments
                    </td>
                    <td>
                        <strong>54</strong> Articles
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>154</strong> Tags
                    </td>
                    <td>
                        <strong>32</strong> Friends
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <small>Sales in last 24h</small>
            <h2 class="no-margins">206 480</h2>
            <div id="sparkline1"></div>
        </div>


    </div>
    <div class="row">

        <div class="col-lg-3">

            <div class="ibox">
                <div class="ibox-content">
                        <h3>About <%= @company.name %></h3>

                    <p class="small">
                        There are many variations of passages of Lorem Ipsum available, but the majority have
                        suffered alteration in some form, by injected humour, or randomised words which don't.
                        <br>
                        <br>
                        If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing
                    </p>

                    <p class="small font-bold">
                        <span><i class="fa fa-circle text-navy"></i> Online status</span>
                        </p>

                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Followers and friends</h3>
                    <p class="small">
                        If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing
                    </p>
                    <!-- <div class="user-friends">
                        <a href=""><img alt="image" class="img-circle" src="img\a3.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a1.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a2.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a4.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a5.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a6.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a7.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a8.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a2.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a1.jpg"></a>
                    </div> -->
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Personal friends</h3>
                    <ul class="list-unstyled file-list">
                        <li><a href=""><i class="fa fa-file"></i> Project_document.docx</a></li>
                        <li><a href=""><i class="fa fa-file-picture-o"></i> Logo_zender_company.jpg</a></li>
                        <li><a href=""><i class="fa fa-stack-exchange"></i> Email_from_Alex.mln</a></li>
                        <li><a href=""><i class="fa fa-file"></i> Contract_20_11_2014.docx</a></li>
                        <li><a href=""><i class="fa fa-file-powerpoint-o"></i> Presentation.pptx</a></li>
                        <li><a href=""><i class="fa fa-file"></i> 10_08_2015.docx</a></li>
                    </ul>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Private message</h3>

                    <p class="small">
                        Send private message to Alex Smith
                    </p>

                    <div class="form-group">
                        <label>Subject</label>
                        <input type="email" class="form-control" placeholder="Message subject">
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea class="form-control" placeholder="Your message" rows="3"></textarea>
                    </div>
                    <button class="btn btn-primary btn-block">Send</button>

                </div>
            </div>

        </div>

        <div class="col-lg-9">
            <% @featured_products.each_slice(2) do |products_group| %>
                <div class="row">
                    <% products_group.each do |product| %>
                    <div class="col-md-6">
                        <div class="ibox">
                            <div class="ibox-content product-box">
                                <% product.product_images.first(1).each do |i| %>
                                   <%= image_tag i.image_url(:large_thumb), class: 'img-responsive' %>
                                <% end %>
                                <% if product.product_images.empty? %>
                                <div class="product-imitation">
                                    [ НЕТ ФОТО ]
                                </div>
                                <% end %>
                                <div class="product-desc">
                                    <span class="product-price">
                                        <%= product.price %> Грн.
                                    </span>
                                    <% if product.category.name %>
                                    <small data-toggle="tooltip" title="<%= product.category.name %>" class="text-muted"><%= product.category.name.truncate(30) %></small>
                                    <% end %>
                                    <a href="<%= catalog_product_path(product.category_id, product) %>" data-toggle="tooltip" title="<%= product.name if product.name %>" class="product-name"> <%= product.name.truncate(20) if product.name %></a>
                                    <div class="small m-t-xs">
                                        <%= sanitize(product.description.truncate(60)) if product.description %>
                                    </div>
                                    <div class="m-t text-righ">
                                        <%= link_to "Подробнее", catalog_product_path(product.category, product), class: "btn btn-xs btn-outline btn-primary" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
                <% end %>
        </div>
    </div>
</div>
<% else %>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-12">
            <h2>У Вас нет компании добавьте свою компанию.</h2>
            <%= link_to "Добавить компанию", new_company_path, class: "btn btn-primary" %>
        </div>
    </div>
</div>
<% end %>

app/views/companies/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Создание компании</h2>
        <ol class="breadcrumb">
            <li><a href="<%= dashboard_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li><a href="<%= companies_path %>">Компании</a></li>
            <li class="active"><strong>Создание компании</strong></li>
        </ol>
    </div>
</div>
<%= render 'form' %>

app/views/companies/show.html.erb
 
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>Профиль</h2>
            <ol class="breadcrumb">
                <li><a href="<%= dashboard_path %>">Главная</a></li>
                <li><a>Профиль компании</a></li>
                <li class="active"><strong><%= @company.name %></strong></li>
            </ol>
        </div>
        <div class="col-lg-2">
        </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-lg m-t-lg">
        <div class="col-md-6">
            <div class="profile-image">
                 
                    <%= image_tag 'images.png', size: "100", class: "iimg-circle circle-border m-b-md", alt: "profile" %>
                
            </div>
            <div class="profile-info">
                <div class="">
                    <div>
                        <h2 class="no-margins">
                            <%= @company.name %>
                        </h2>
                        <h4><%#= raw current_user.post %> <%#= raw current_user.company.name if current_user.company %></h4>
                        <small>
                            <%= raw @company.description %>
                        </small>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <table class="table small m-b-xs">
                <tbody>
                <tr>
                    <td><strong><%= @company.products.count %></strong>Товаров</td>
                    <td><strong><%#= @company.products.categories.count %></strong>Категории</td>
                </tr>
                <tr>
                    <td>
                        <strong>61</strong> Comments
                    </td>
                    <td>
                        <strong>54</strong> Articles
                    </td>
                </tr>
                <tr>
                    <td>
                        <strong>154</strong> Tags
                    </td>
                    <td>
                        <strong>32</strong> Friends
                    </td>
                </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-3">
            <small>Sales in last 24h</small>
            <h2 class="no-margins">206 480</h2>
            <div id="sparkline1"></div>
        </div>


    </div>
    <div class="row">

        <div class="col-lg-3">

            <div class="ibox">
                <div class="ibox-content">
                        <h3><%= @company.name %></h3>

                    <p class="small">
                        There are many variations of passages of Lorem Ipsum available, but the majority have
                        suffered alteration in some form, by injected humour, or randomised words which don't.
                        <br>
                        <br>
                        If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing
                    </p>

                    <p class="small font-bold">
                        <span><i class="fa fa-circle text-navy"></i> Online status</span>
                        </p>

                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Followers and friends</h3>
                    <p class="small">
                        If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't
                        anything embarrassing
                    </p>
                    <!-- <div class="user-friends">
                        <a href=""><img alt="image" class="img-circle" src="img\a3.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a1.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a2.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a4.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a5.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a6.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a7.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a8.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a2.jpg"></a>
                        <a href=""><img alt="image" class="img-circle" src="img\a1.jpg"></a>
                    </div> -->
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Personal friends</h3>
                    <ul class="list-unstyled file-list">
                        <li><a href=""><i class="fa fa-file"></i> Project_document.docx</a></li>
                        <li><a href=""><i class="fa fa-file-picture-o"></i> Logo_zender_company.jpg</a></li>
                        <li><a href=""><i class="fa fa-stack-exchange"></i> Email_from_Alex.mln</a></li>
                        <li><a href=""><i class="fa fa-file"></i> Contract_20_11_2014.docx</a></li>
                        <li><a href=""><i class="fa fa-file-powerpoint-o"></i> Presentation.pptx</a></li>
                        <li><a href=""><i class="fa fa-file"></i> 10_08_2015.docx</a></li>
                    </ul>
                </div>
            </div>

            <div class="ibox">
                <div class="ibox-content">
                    <h3>Private message</h3>

                    <p class="small">
                        Send private message to Alex Smith
                    </p>

                    <div class="form-group">
                        <label>Subject</label>
                        <input type="email" class="form-control" placeholder="Message subject">
                    </div>
                    <div class="form-group">
                        <label>Message</label>
                        <textarea class="form-control" placeholder="Your message" rows="3"></textarea>
                    </div>
                    <button class="btn btn-primary btn-block">Send</button>

                </div>
            </div>

        </div>

        <div class="col-lg-9">
            <% @featured_products.each_slice(2) do |products_group| %>
                <div class="row">
                    <% products_group.each do |product| %>
                    <div class="col-md-6">
                        <div class="ibox">
                            <div class="ibox-content product-box">
                                <% product.product_images.first(1).each do |i| %>
                                   <%= image_tag i.image_url(:large_thumb), class: 'img-responsive' %>
                                <% end %>
                                <% if product.product_images.empty? %>
                                <div class="product-imitation">
                                    [ НЕТ ФОТО ]
                                </div>
                                <% end %>
                                <div class="product-desc">
                                    <span class="product-price">
                                        <%= product.price %> Грн.
                                    </span>
                                    <% if product.category.name %>
                                    <small data-toggle="tooltip" title="<%= product.category.name %>" class="text-muted"><%= product.category.name.truncate(30) %></small>
                                    <% end %>
                                    <a href="<%= catalog_product_path(product) %>" data-toggle="tooltip" title="<%= product.name if product.name %>" class="product-name"> <%= product.name.truncate(20) if product.name %></a>
                                    <div class="small m-t-xs">
                                        <%= sanitize(product.description.truncate(60)) if product.description %>
                                    </div>
                                    <div class="m-t text-righ">
                                        <%= link_to "Подробнее", catalog_product_path(product), class: "btn btn-xs btn-outline btn-primary" %>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <% end %>
                </div>
                <% end %>
        </div>
    </div>
</div>
 