config/routes.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
Rails.application.routes.draw do
  
  get 'welcome/index'
  root to: "catalog/welcome#index"
  
  namespace :account do
    # resources after registration on devise add user first_name, last_name ... select role etc...
    resources :steps, only: [:show, :update]
    # resources manufacturer registration company, trademark, product etc...
    resources :manufacturer_steps, only: [:show, :update]
    # resources distributor registration company etc...
    resources :distributor_steps, only: [:show, :update]
  end

  namespace :catalog do
    get "/" => "products#index"
    resources :trademarks, only: [:index, :show]
    resources :companies, only: [:index, :show]
    # resources :categories, only: [:index, :show] do
    #   resources :products, only: [:index, :show] do
    #     member do
    #       get :like
    #       get :unlike
    #     end
    #   end
    # end
    
    resources :categories, only: [:index, :show]
    resources :products, only: [:index, :show] do
      member do
        put :like
        put :unlike
        put :favorite
        put :unfavorite
      end
    end
  resources :customers, only: [:index, :show] do
      member do
        put :follow
        put :unfollow
      end
    end
  end
  
  namespace :administration do
    get "/" => "dashboard#index"
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end

    resources :trademarks, only: [:index, :show, :edit, :update]
    #match 'roles/index', to: 'roles#index', as: :roles, via: 'get'
    resources :customers, only: [:index, :show, :edit, :update] do
      collection do
        get :manufacturers
        get :distributors
        get :simple_customers
        get :all
      end
    end
    resources :employees, only: [:index, :show, :edit, :update] do
      collection do
        get :administrators
        get :moderators
        get :operators
        get :all
      end
    end
    resources :users
    resources :companies, only: [:index, :show, :edit, :update] do
      collection do
        get :published#, path: "/states/published"
        get :pending
        get :editing
        get :denied
        get :trashed
        get :removed
      end
    end
    scope "/stadistics" do
      resources :activities
    end
    scope "/catalog" do
      resources :categories
      resources :products, only: [:index, :show, :edit, :update] do
         collection do
          match 'search' => 'products#search', via: [:get, :post], as: :search
        end
      end
    end

    scope "/account" do

      match 'dashboard',  to: 'dashboard#index', as: :dashboard, via: [:get] 
      match 'profile', to: 'account#profile', as: :profile, via: 'get'

    end
    scope "/administration" do
      #match 'employees/list', to: 'employees#index', as: :employees, via: 'get'
      # TheRoleManagementPanel::Routes.mixin(self)
      resources :roles
      resources :activities
    end
  end

  #scope :account do
 
    resources :users do
      member do
        put :follow
        put :unfollow
      end
    end

    resources :product_images
    resources :companies
    resources :trademarks
    resources :categories, only: [:index, :show] do
      member do
        get :get_subcategories, defaults: { format: "js" }
      end
    end
    resources :subcategories
    resources :products

 
    resources :orders do
      collection do
        post :search
      end
      member do
        post :accept
        post :reject
        post :ship
        get :despatch_note
      end
    end
    
    scope "/account" do
      get 'dashboard',  to: 'dashboard#index', as: :dashboard
      get 'profile', to: 'account#profile', as: :profile
      match 'profile/update', to: 'account#update_profile', as: :update_profile, via: [:patch, :put] 
      get 'profile/edit', to: 'account#edit_profile', as: :edit_profile
      match 'my_favorite_products', to: 'account#my_favorite_products', as: :my_favorite_products, via: 'get'
    end
     
    #TheRoleManagementPanel::Routes.mixin(self)
    #devise_for :users, :path => '', controllers: {registrations: 'users/registrations'}
    
  #end

  devise_for :users, :path => '', controllers: { registrations: "registrations" }
  %w( 404 422 500 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/controllers/administration/products_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Administration::ProductsController < ApplicationController
  before_action :login_required
  before_action :role_required
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  # GET /administration/products
  # GET /administration/products.json
  def index
      @products = Product.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /administration/products/1
  # GET /administration/products/1.json
  def show
    #@product_images = @products.product_images.all
    @product_images = @product.product_images
  end

  # GET /administration/products/new
  # def new
  #   @product = Product.new
  #   @product_image = @product.product_images.build
  # end

  # GET /administration/products/1/edit
  def edit
     @product_image = @product.product_images.build
     @product_images = @product.product_images
  end

  # POST /administration/products
  # POST /administration/products.json
  # def create
  #   @product = Product.new(product_params)

  #   respond_to do |format|
  #     if @product.save
  #       params[:product_images]['image'].each do |i|
  #         @product_image = @product.product_images.create!(:image => i)
  #       end
  #       format.html { 
  #         redirect_to administration_products_path
  #         toast :success, "Товар был успешно создан."
  #       }
  #       format.json { render :show, status: :created, location: @product }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @product.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /administration/products/1
  # PATCH/PUT /administration/products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        params[:product_images]['image'].each do |i|
          @product_image = @product.product_images.create!(:image => i)
        end
        format.html { 
          redirect_to administration_products_path
          toast :success, "Товар был успешно обновлен."
        }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administration/products/1
  # DELETE /administration/products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { 
        redirect_to administration_products_url
        toast :success, "Товар был успешно удален."
      }
      format.json { head :no_content }
    end
  end

  private

    def search_params
      default_params = {}
      default_params.merge({user_id_eq: current_user.id}) if signed_in?
      # more logic here
      params[:q].merge(default_params)
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def set_search
      @search = Product.search(params[:q])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(
        :user_id,
        :category_id,
        :name,
        :on_sale,
        :ean13,
        :upc,
        :quantity,
        :minimal_quantity,
        :price,
        :wholesale_price,
        :unity,
        :additional_shipping_cost,
        :reference,
        :supplier_reference,
        :width,
        :height,
        :depth,
        :weight,
        :available_for_order,
        :available_date,
        :show_price,
        :visibility,
        :description,
        :short_description,
        :active,
        :featured,
        :stock_control,
        :meta_title,
        :meta_keywords,
        :meta_description,
        product_images_attributes: [:id, :product_id, :image]
      )
    end
end

app/controllers/catalog/categories_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::CategoriesController < ApplicationController
  before_action :set_category, only: [:show]
  layout 'catalog'
  
  # GET /catalog/categories
  # GET /catalog/categories.json
  def index
    @categories = Category.all
  end

  # GET /catalog/categories/1
  # GET /catalog/categories/1.json
  def show
    @products = Product.filter(params.slice(:status, :location, :starts_with)).last(12)
    @categories = Category.find(params[:id]).childrens
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def trademark_params
    #   params.require(:trademark).permit(:name, :description, :user_id, :company, :company_id)
    # end
end

app/controllers/catalog/companies_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::CompaniesController < ApplicationController
  before_action :set_company, only: [:show]
  layout 'catalog'
  
  # GET /catalog/companies
  # GET /catalog/companies.json
  def index
    #@companies = Company.all
    @companies = Company.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /catalog/companies/1
  # GET /catalog/companies/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/catalog/customers_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::CustomersController < ApplicationController
  # before_action :authenticate_user!
  before_action :set_customer, only: [:show, :follow, :unfollow]
  layout 'catalog'
  
  def show
    if @customer.company.try(:any?)
      @featured_products = @customer.company.products.filter(params.slice(:status, :location, :starts_with)).last(12)
    else
      #redirect_to :root
      @featured_products = nil
      toast :error, "Ошибка."
    end
  end

  def follow
    respond_to do |format|
      if current_user.follow!(@customer)
        format.js
      end
    end 
  end

  def unfollow
    respond_to do |format|
      if current_user.unfollow!(@customer)
         format.js
      end
    end
  end

  private
      # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = User.find(params[:id])
    end
end

app/controllers/catalog/products_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::ProductsController < ApplicationController
  before_action :set_product, only: [:show, :like, :unlike, :favorite, :unfavorite]
  layout 'catalog'
  helper_method :sort_column, :sort_direction
  
  # GET /catalog/products
  # GET /catalog/products.json
  def index
      @products = Product.filter(params.slice(:status, :location, :starts_with)).paginate(:page => params[:page], :per_page => 12)
      #@products = Product.paginate(:page => params[:page], :per_page => 30)    
  end

  # GET /catalog/products/1
  # GET /catalog/products/1.json
  def show
    #@product_images = @products.product_images.all
    @product_images = @product.product_images
  end
 
  def like
    respond_to do |format|
      if current_user.like!(@product)
        format.js  
      end   
    end
  end

  def unlike
    respond_to do |format|
      if current_user.unlike!(@product)
        format.js  
      end
    end
  end

  def favorite
    respond_to do |format|
      if current_user.mention!(@product)
        format.js
      end
    end
  end

  def unfavorite
    respond_to do |format|
      if current_user.unmention!(@product)
        format.js
      end
    end
  end

  private

    def search_params
      default_params = {}
      default_params.merge({user_id_eq: current_user.id}) if signed_in?
      # more logic here
      params[:q].merge(default_params)
    end

    def sort_column
      Product.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def set_search
      @search = Product.search(params[:q])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

end

app/controllers/catalog/socializations_controller.rb
class Catalog::SocializationsController < ApplicationController
  before_action :load_socializable

  def follow
    current_user.follow!(@socializable)
    render json: { follow: true }
  end

  def unfollow
    current_user.unfollow!(@socializable)
    render json: { follow: false }
  end

private
  def load_socializable
    @socializable =
      case
      when id = params[:comment_id] # Must be before :item_id, since it's nested under it.
        @community.comments.find(id)
      when id = params[:item_id]
        @community.items.find(id)
      when id = params[:user_id]
        User.find(id)
      when id = params[:category_id]
        @community.categories.find_by_id(id)
      else
        raise ArgumentError, "Unsupported socializable model, params: " +
                             params.keys.inspect
      end
    raise ActiveRecord::RecordNotFound unless @socializable
  end  
end

app/controllers/catalog/trademarks_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::TrademarksController < ApplicationController
  before_action :set_trademark, only: [:show]
  layout 'catalog'
  
  # GET /catalog/trademarks
  # GET /catalog/trademarks.json
  def index
    @trademark = Trademark.all
  end

  # GET /catalog/trademarks/1
  # GET /catalog/trademarks/1.json
  def show
    @featured_products = Product.filter(params.slice(:status, :location, :starts_with)).last(12)
  end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trademark
      @trademark = Trademark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def trademark_params
    #   params.require(:trademark).permit(:name, :description, :user_id, :company, :company_id)
    # end
end

app/controllers/catalog/welcome_controller.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
class Catalog::WelcomeController < ApplicationController
  layout 'catalog'
  
  def index
  	@featured_products = Product.filter(params.slice(:status, :location, :starts_with)).last(12)
	@root_categories = Category.without_parent
  end

end

app/helpers/administration/product_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Administration::ProductHelper 
end

app/helpers/catalog/companies_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::CompaniesHelper  
end

app/helpers/catalog/customers_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::CustomersHelper  
end

app/helpers/catalog/trademarks_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::TrademarksHelper
end

app/helpers/catalog/welcome_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module Catalog::WelcomeHelper
	# Devise methods for forms
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/products_helper.rb
=begin
 Author: Andrey Zhuk
 Copyright (C) 2015 Zettheme. All Rights Reserved. https://zettheme.com
 Support:  support@zettheme.com
=end
module ProductsHelper 
end

app/views/catalog/products/_favorite.html.erb
<%= link_to "Добавить в избранное", favorite_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-primary" %>

app/views/catalog/products/_likers.html.erb
<% if signed_in? %>
  <% if current_user.likes?(@product)  %>
      <% if @product.likers(User).count > 1 %>
        Вам и еще <% @product.likers(User).reject {|i| i == current_user}.each do |liker|  %> 
          <%= link_to full_name_user(liker), catalog_customer_path(liker) %> 
        <% end %> 
        это понравилось. 
      <% elsif @product.likers(User).count >= 4  %>
        Вам и еще <%= @product.likers(User).count %> это понравилось.
      <% else %>
      Вам это нравится.
      <% end %>
  <% elsif @product.likers(User).count <= 3  %>
    <% @product.likers(User).reject {|i| i == current_user}.each do |liker|  %> 
          <%= link_to full_name_user(liker), catalog_customer_path(liker) %> 
        <% end %> 
    это понравилось.
  <% else %>
      <%= @product.likers(User).count %> пользователям это нравится
  <% end %>
<% end %>

 

app/views/catalog/products/_unfavorite.html.erb
<%= link_to "Убрать из избранных?", unfavorite_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-danger" %>

app/views/catalog/products/_unlike.html.erb
<%= link_to "Не нравится", unlike_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-danger" %>

app/views/catalog/products/edit.html.erb
<%= render 'form' %>

app/views/catalog/products/favorite.js.erb
<% if current_user.mentions?(@product) %>
  $('#favorite_button').html('<%= escape_javascript(render "unfavorite") %>');
<% else %>
  $('#favorite_button').html('<%= escape_javascript(render "favorite") %>');
<% end %>

app/views/catalog/products/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>E-commerce grid</h2>
        <ol class="breadcrumb">
            <li><a href="<%= root_path %>">Главная</a></li>
            <li><a>E-commerce</a></li>
            <li class="active">
                <strong>Products grid</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <% @products.each_slice(4) do |products_group| %>
    <div class="row">
        <% products_group.each do |product| %>
        <div class="col-md-3">
            <div class="ibox">
                <div class="ibox-content product-box">
                    <% product.product_images.first(1).each do |i| %>
                       <%= image_tag i.image_url(:large_thumb), style: "width: 260px; height: 200px;" %>
                    <% end %>
                    <% if product.product_images.empty? %>
                    <div class="product-imitation">
                        [ НЕТ ФОТО ]
                    </div>
                    <% end %>
                    <div class="product-desc">
                        <span class="product-price">
                            <%= product.price %> Грн.
                        </span>
                        <small data-toggle="tooltip" title="<%= product.category.name if product.category.name %>" class="text-muted"><%= product.category.name.truncate(30) if product.category.name %></small>
                        <a href="<%= catalog_product_path(product) %>" data-toggle="tooltip" title="<%= product.name if product.name %>" class="product-name"> <%= product.name.truncate(20) if product.name %></a>
                        <div class="small m-t-xs">
                            <%= sanitize(product.description.truncate(60)) if product.description %>
                        </div>
                        <div class="m-t text-righ">
                            <%= link_to "Подробнее", catalog_product_path(product), class: "btn btn-xs btn-outline btn-primary" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <% end %>
    </div>
    <% end %>
     <ul class="pagination pull-right"><%= will_paginate @products %></ul>
</div>

app/views/catalog/products/like.js.erb
<% if current_user.likes?(@product) %>
  $('#like_button').html('<%= escape_javascript(render "unlike") %>');
<% else %>
  $('#like_button').html('<%= escape_javascript(render "like") %>');
<% end %>


$('#likers').html('<%= escape_javascript(render "likers") %>');

app/views/catalog/products/likers.js.erb
$('#likers').html('<%= escape_javascript(render "likers") %>');

app/views/catalog/products/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/catalog/products/show.html.erb
<% content_for :css do %>
<%= stylesheet_link_tag "plugins/slick/slick" %>
<%= stylesheet_link_tag "plugins/slick/slick-theme" %>
<% end %>

<% content_for :js do %>
<%= javascript_include_tag "plugins/slick/slick.min" %>
<script>
    $(document).ready(function(){
        $('.product-images').slick({
            dots: true
        });
    });
</script>
<% end %>

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2>Каталог - товары - Подробно о продукте - <%= @product.name %></h2>
        <ol class="breadcrumb">
            <li><a href="<%= root_path %>">Главная</a></li>
            <li><a>Каталог</a></li>
            <li><a href="<%= catalog_products_path %>"><%= @product.category.name %></a></li>
            <li class="active"><strong><%= @product.name %></strong></li>
        </ol>
    </div>
    <div class="col-lg-2">
        
    </div>
</div>
 
<div class="wrapper wrapper-content">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox product-detail">
                <div class="ibox-content">
                    <div class="row">
                        <div class="col-md-5">
                            <div class="product-images">
                                <% @product_images.each do |i| %>
                                  <%= image_tag i.image_url %>
                                <% end %>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="text-right">
                                        <!-- <i class="fa fa-thumbs-up "></i> -->
                                        <div id="likers">
                                          <%= render "likers" %>
                                        </div>
                                        <%# unless signed_in? %>
                                             <!-- <%#= @product.likers(User).count %> пользователям это нравится -->
                                        <%# end %>

                                      <div id="like_button">
                                        <% if signed_in? %>
                                            <% if current_user.likes?(@product) %>
                                                <%= link_to "Не нравится", unlike_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-danger" %>
                                            <% else %>
                                                <%= link_to "Нравится", like_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-primary" %>
                                            <% end %>
                                        <% end %>
                                      </div> <br>

                                      <div id="favorite_button">
                                         
                                        <% if signed_in? %>
                                            <% if current_user.mentions?(@product) %>
                                              <%= link_to "Убрать из избранных?", unfavorite_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-danger" %>
                                            <% else %>
                                              <%= link_to "Добавить в избранное", favorite_catalog_product_path(@product), remote: true, method: :put, class: "btn btn-xs btn-primary" %>
                                            <% end %>
                                        <% end %>
                                      </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-7">
                            <h1 class="font-bold m-b-xs"><%= @product.name %></h1>
                            <small>Категория - <%= link_to @product.category.name, catalog_category_path(@product.category) %></small>
                            <div class="m-t-md">
                                <div class="row">
                                    <div class="col-xs-4">
                                        <ul class="list-unstyled">
                                            <li>Штрифкод: <%= @product.ean13 %>12345678958</li>
                                            <li>Артикул: <%= @product.reference %></li>
                                        </ul>
                                    </div>
                                    <div class="col-xs-5">
                                        <h4>Информация о компании</h4>
                                        <ul class="list-unstyled">
                                            <li>Компания производитель: <%= link_to @product.company.name, catalog_company_path(@product.company) if @product.company %></li>
                                            <li>Торговая марка компании: <%= link_to @product.trademark.name, catalog_trademark_path(@product.trademark) if @product.trademark %></li>
                                            <hr>
                                            <li>Город: <%= @product.company.city %></li>
                                        </ul>
                                    </div>
                                    <div class="col-xs-3">
                                        <%= image_tag @product.company.logo_url(:profile) %>
                                    </div>
                                </div>
                                <div class="btn-group">
                                    <%= link_to "Связаться с представителем", catalog_customer_path(@product.user.id), class: "btn btn-primary btn-sm" %>
                                </div>
                                
                            </div>
                            
                            <hr>
                            <h4>Описание товара</h4>
                            <div class="small text-muted">
                                 
                            </div>
                            <dl class="small m-t-md">
                                <dt>Дополнительная информация</dt>
                                <%= @product.description.html_safe if @product.description %>
                            </dl>
                             
                        </div>
                    </div>
                </div>
                <div class="ibox-footer">
                    <span class="pull-right">
                        Информация актуальна с - <i class="fa fa-clock-o"></i> <%= I18n.l @product.updated_at, format: :long  %>
                    </span>
                    Автор этой информации <%= link_to full_name_user(@product.user), catalog_customer_path(@product.user) %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/catalog/products/unfavorite.js.erb
<% if current_user.mentions?(@product) %>
  $('#favorite_button').html('<%= escape_javascript(render "unfavorite") %>');
<% else %>
  $('#favorite_button').html('<%= escape_javascript(render "favorite") %>');
<% end %>

app/views/catalog/products/unlike.js.erb
<% if current_user.likes?(@product) %>
  $('#like_button').html('<%= escape_javascript(render "unlike") %>');
<% else %>
  $('#like_button').html('<%= escape_javascript(render "like") %>');
<% end %>

$('#likers').html('<%= escape_javascript(render "likers") %>');